### ISSUE TITLE
关于 Commit(上传/删除 文件) 的一些建议

### ISSUE THREAD

**Issue by gytxtx** [Khrisma13/barank#1]
![image](https://github.com/Khrisma13/barank/assets/62281844/3b752697-b8a7-4c8c-a8f1-fe677b7e8439)

你好！我注意到你在删除文件时一个一个操作，这确实有点繁琐。为了更方便地管理文件，我建议你尝试使用 [GitHub Desktop](https://desktop.github.com/)，这是一个免费的开源应用程序，可以帮助你处理托管在 GitHub 或其他 Git 托管服务上的代码。

GitHub Desktop 具有图形用户界面，可以让你在不使用命令行的情况下执行提交、推送更改等 Git 命令。以下是一些使用 GitHub Desktop 的好处：

1. **批量提交文件：** 你可以一次性提交多个文件，而不需要逐个操作。
2. **批量删除文件：** 同样，你可以轻松删除多个文件。
3. **撤销提交：** 如果出现错误，你可以撤销提交，避免不必要的麻烦。

如果你不太熟悉 GitHub Desktop 的英文界面，你可以在网络上寻找一些第三方的 GitHub Desktop 汉化工具，这样你就能看懂它的界面了

---

假如你有别的问题，请联系我，我会尽我所能的为你解答！

**Comment by Khrisma13** [comment]
谢谢您提醒。
我是因为这个项目才开始使用GitHub，并且我目前只有这1个项目需要维护（个人主站做好后基本不用再动）。因此我没有配置Git，嫌麻烦。
在此之前我还没有听说过GitHub Desktop，之后我会下载使用它的。
也谢谢您支持蔚蓝档案学生喜好排序。
